"""
Windows De-fender — Main Entry Point
=============================================
A humorous "Useless Project" that does the opposite of an antivirus:
  - Clean files get DELETED (moved to a safe folder)
  - Threats get PRESERVED (copied to the museum)

⚠️  DEMO / JOKE PROJECT — No real malware is used or created.
    All "threats" are harmless .txt files generated by the app.

Technology: Python, CustomTkinter, SQLite
"""

import os
os.environ.setdefault("PYTHONUTF8", "1")

import customtkinter as ctk
import sys

# Ensure the project root is in the path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from ui.app import AntiAntivirusApp


def main():
    """Launch the Windows De-fender application."""
    # Set CustomTkinter appearance to Windows 7 Aero Light
    ctk.set_appearance_mode("light")
    ctk.set_default_color_theme("blue")

    # Create and run the application
    app = AntiAntivirusApp()
    app.mainloop()


if __name__ == "__main__":
    main()
